# ------------- Twitter Keys -------------
twit_api_key: VWMVPYOCe23Ps7ntUx3b6K8pR
twit_api_secret: EW8QdSQoZDcSP8nFLpcl5Sh35M2pQVEMWw4Z7HCw962c2CAmDP
twit_bearer_token: AAAAAAAAAAAAAAAAAAAAAG5YewEAAAAAaEMS0PNRVDHP3a0aakpKD9aSI0k%3DRMGKq0Q4XgtYu4LsXjpxL8veXxlEwcyDWp5wHaeHfV4CFGyUuk
twit_access_token: 1491807320287981573-2cGHPU9zkOGruIZHcBI7JoVs0NcQwz
twit_access_secret: ZGmZcgHV1PHCm25IDpUNOUcSsmOSQwibxpX2JIW2ZpMLN
uploads: "imagefolder?"

# ------------- Next Keys -------------